/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/sculpt_360.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/sculpt_360.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.moi_IM.geometry} material={nodes.moi_IM.material} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.001']} scale={55.254} />
    </group>
  )
}

useGLTF.preload('/sculpt_360.glb')
